version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres_prova
    restart: always
    environment:
      POSTGRES_USER: joao
      POSTGRES_PASSWORD: 1308
      POSTGRES_DB: prova
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
