"""Update nas tabelas

Revision ID: 34cb766c1a57
Revises: e79fe5732407
Create Date: 2025-02-13 22:52:55.552943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34cb766c1a57'
down_revision: Union[str, None] = 'e79fe5732407'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ObrigacaoAcessoria_empresa_id_fkey', 'ObrigacaoAcessoria', type_='foreignkey')
    op.create_foreign_key(None, 'ObrigacaoAcessoria', 'Empresa', ['empresa_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ObrigacaoAcessoria', type_='foreignkey')
    op.create_foreign_key('ObrigacaoAcessoria_empresa_id_fkey', 'ObrigacaoAcessoria', 'Empresa', ['empresa_id'], ['id'])
    # ### end Alembic commands ###
