"""Update nas tabelas

Revision ID: e79fe5732407
Revises: 4c7fa1683356
Create Date: 2025-02-13 21:01:26.996300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e79fe5732407'
down_revision: Union[str, None] = '4c7fa1683356'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ObrigacaoAcessoria_empresa_id_key', 'ObrigacaoAcessoria', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('ObrigacaoAcessoria_empresa_id_key', 'ObrigacaoAcessoria', ['empresa_id'])
    # ### end Alembic commands ###
